/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Feedback;

import UI.DatabaseConnection;
import UI.MainMenuJFrame;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author AnjanaSruthiR
 */
public class ViewFeedbackJFrame extends javax.swing.JFrame {

    private final MainMenuJFrame parent;

    /**
     * Creates new form ViewFeedbackJFrame
     */
    public ViewFeedbackJFrame(MainMenuJFrame parent) {
        initComponents();
        this.parent = parent;
        loadFeedbackData();
    }

    private void loadFeedbackData() {
        DefaultTableModel model = (DefaultTableModel) TblFeedback.getModel();
        model.setRowCount(0); // Clear existing rows

        String query = "SELECT F.FeedbackID, F.FeedbackDate, F.Rating, F.Comments, "
                + "C.FirstName AS CustomerFirstName, C.LastName AS CustomerLastName, "
                + "B.BookingID "
                + "FROM Feedback F "
                + "JOIN Customer CU ON F.CustomerID = CU.Customer_PersonID "
                + "JOIN Person C ON CU.Customer_PersonID = C.PersonID "
                + "JOIN Booking B ON F.BookingID = B.BookingID";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(query); ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("FeedbackID"),
                    rs.getDate("FeedbackDate"),
                    rs.getInt("Rating"),
                    rs.getString("Comments"),
                    rs.getString("CustomerFirstName") + " " + rs.getString("CustomerLastName"),
                    rs.getInt("BookingID")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading feedback data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TblFeedback = new javax.swing.JTable();
        BtnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Feedbacks");

        BtnBack.setText("<-Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        TblFeedback.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Feedback ID", "Date", "Rating", "Comments", "Customer", "Booking ID"
            }
        ));
        jScrollPane2.setViewportView(TblFeedback);

        BtnDetails.setText("Details");
        BtnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(BtnBack)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnDetails)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBack))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(BtnDetails)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        this.dispose();
        if (parent != null) {
            parent.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetailsActionPerformed
        int selectedRow = TblFeedback.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a feedback entry to view details.");
            return;
        }

        int feedbackID = (int) TblFeedback.getValueAt(selectedRow, 0);

        String query = "SELECT F.FeedbackDate, F.Rating, F.Comments, "
                + "C.FirstName AS CustomerFirstName, C.LastName AS CustomerLastName, "
                + "B.BookingID, B.BookingDate, B.StartDate, B.EndDate, B.TotalAmount, "
                + "P.FirstName AS EmployeeFirstName, P.LastName AS EmployeeLastName, "
                + "E.JobTitle, E.Department "
                + "FROM Feedback F "
                + "JOIN Customer CU ON F.CustomerID = CU.Customer_PersonID "
                + "JOIN Person C ON CU.Customer_PersonID = C.PersonID "
                + "JOIN Booking B ON F.BookingID = B.BookingID "
                + "JOIN Employee E ON B.EmployeeID = E.Employee_PersonID "
                + "JOIN Person P ON E.Employee_PersonID = P.PersonID "
                + "WHERE F.FeedbackID = ?";

        try (Connection conn = DatabaseConnection.getConnection(); PreparedStatement stmt = conn.prepareStatement(query)) {

            stmt.setInt(1, feedbackID);
            ResultSet rs = stmt.executeQuery();

            if (rs.next()) {
                String details = String.format(
                        "<html><body>"
                        + "<b>Feedback Date:</b> %s<br>"
                        + "<b>Rating:</b> %d<br>"
                        + "<b>Comments:</b> %s<br><br>"
                        + "<b>Customer:</b> %s %s<br>"
                        + "<b>Booking ID:</b> %d<br>"
                        + "<b>Booking Dates:</b> %s to %s<br>"
                        + "<b>Total Amount:</b> %.2f<br><br>"
                        + "<b>Employee:</b> %s %s<br>"
                        + "<b>Job Title:</b> %s<br>"
                        + "<b>Department:</b> %s"
                        + "</body></html>",
                        rs.getDate("FeedbackDate"),
                        rs.getInt("Rating"),
                        rs.getString("Comments"),
                        rs.getString("CustomerFirstName"),
                        rs.getString("CustomerLastName"),
                        rs.getInt("BookingID"),
                        rs.getDate("StartDate"),
                        rs.getDate("EndDate"),
                        rs.getDouble("TotalAmount"),
                        rs.getString("EmployeeFirstName"),
                        rs.getString("EmployeeLastName"),
                        rs.getString("JobTitle"),
                        rs.getString("Department")
                );

                JOptionPane.showMessageDialog(this, details, "Feedback Details", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Feedback details not found.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error fetching feedback details: " + e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFeedbackJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewFeedbackJFrame(null).setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnDetails;
    private javax.swing.JTable TblFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
