/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Customer;

import UI.DatabaseConnection;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author AnjanaSruthiR
 */
public class AddCustomerJFrame extends javax.swing.JFrame {

    private final ManageCustomersJFrame parent;

    /**
     * Creates new form AddCustomerJFrame
     */
    public AddCustomerJFrame(ManageCustomersJFrame parent) {
        initComponents();
        this.parent = parent;
        populateGenderCombo();
        populatePaymentMethodCombo();
        loadAddressIDs();
        TxtFirstName.requestFocusInWindow();

    }

    private void loadAddressIDs() {
        try (Connection conn = DatabaseConnection.getConnection(); Statement stmt = conn.createStatement(); ResultSet rs = stmt.executeQuery("SELECT AddressID, CONCAT(Street, ', ', City, ', ', State) AS Address FROM Address")) {

            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
            model.addElement("Select--"); // Default option
            while (rs.next()) {
                model.addElement(rs.getInt("AddressID") + " - " + rs.getString("Address"));
            }
            ComboAddress.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading Address IDs.");
        }
    }

    private void populateGenderCombo() {
        ComboGender.setModel(new DefaultComboBoxModel<>(new String[]{"Select--", "M", "F", "Other"}));
    }

    private void populatePaymentMethodCombo() {
        ComboPreferredPM.setModel(new DefaultComboBoxModel<>(new String[]{"Select--", "Credit Card", "Debit Card", "Cash", "Bank Transfer"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TxtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtdateOfBirth = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtPhoneNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtNationality = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ComboGender = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        TxtLED = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TxtDLN = new javax.swing.JTextField();
        BtnSave = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ComboPreferredPM = new javax.swing.JComboBox<>();
        ComboAddress = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Preferred Payment Method");

        jLabel3.setText("Date Of Birth (yyyy-mm-dd)");

        jLabel4.setText("Phone Number");

        jLabel5.setText("Nationality");

        jLabel6.setText("Last Name");

        jLabel7.setText("Gender");

        jLabel8.setText("Email");

        jLabel9.setText("Address ID");

        ComboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select--", "M", "F", "Other" }));
        ComboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboGenderActionPerformed(evt);
            }
        });

        jLabel10.setText("License Expiry Date");

        jLabel11.setText("Driver License Number");

        BtnSave.setText("Save");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        BtnBack.setText("<- Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Create Customer details");

        ComboPreferredPM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select--", "Credit Card", "Debit Card", "Cash", "Bank Transfer" }));

        ComboAddress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select--", "Item1" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(44, 44, 44)
                        .addComponent(TxtDLN, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addComponent(TxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44)
                        .addComponent(TxtdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLED, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(ComboPreferredPM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)
                        .addComponent(TxtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(ComboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(44, 44, 44)
                        .addComponent(TxtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(ComboAddress, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(BtnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(BtnBack)
                        .addGap(153, 153, 153)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBack)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ComboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ComboAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtDLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(TxtLED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ComboPreferredPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(72, 72, 72)
                .addComponent(BtnSave)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboGenderActionPerformed

    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        try (Connection conn = DatabaseConnection.getConnection()) {
            // Fetch and validate values
            String firstName = TxtFirstName.getText();
            String lastName = TxtLastName.getText();
            String dobText = TxtdateOfBirth.getText();
            String licenseExpiryText = TxtLED.getText();

            // Validate gender
            if (ComboGender.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a valid gender.");
                return;
            }
            String gender = ComboGender.getSelectedItem().toString();

            // Validate dates
            java.sql.Date dob, licenseExpiryDate;
            try {
                dob = java.sql.Date.valueOf(dobText);
                licenseExpiryDate = java.sql.Date.valueOf(licenseExpiryText);
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, "Please enter valid dates in the format YYYY-MM-DD.");
                return;
            }

            // Other inputs
            String phoneNumber = TxtPhoneNumber.getText();
            String email = TxtEmail.getText();
            String nationality = TxtNationality.getText();

            // Validate address
            if (ComboAddress.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a valid address.");
                return;
            }
            int addressID = Integer.parseInt(ComboAddress.getSelectedItem().toString().split(" - ")[0]);

            // Validate payment method
            if (ComboPreferredPM.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Please select a preferred payment method.");
                return;
            }
            String preferredPaymentMethod = ComboPreferredPM.getSelectedItem().toString();

            String driverLicenseNumber = TxtDLN.getText();

            // Insert into Person
            String insertPersonSQL = "INSERT INTO Person (Person_Type, FirstName, LastName, DateOfBirth, Gender, PhoneNumber, Email, Nationality, AddressID) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement personStmt = conn.prepareStatement(insertPersonSQL, Statement.RETURN_GENERATED_KEYS);
            personStmt.setString(1, "CUS");
            personStmt.setString(2, firstName);
            personStmt.setString(3, lastName);
            personStmt.setDate(4, dob);
            personStmt.setString(5, gender);
            personStmt.setString(6, phoneNumber);
            personStmt.setString(7, email);
            personStmt.setString(8, nationality);
            personStmt.setInt(9, addressID);
            personStmt.executeUpdate();

            ResultSet rs = personStmt.getGeneratedKeys();
            int personID = rs.next() ? rs.getInt(1) : 0;

            // Insert into Customer
            String insertCustomerSQL = "INSERT INTO Customer (Customer_PersonID, LicenseExpiryDate, PreferredPaymentMethod, DriverLicenseNumber) VALUES (?, ?, ?, ?)";
            PreparedStatement customerStmt = conn.prepareStatement(insertCustomerSQL);
            customerStmt.setInt(1, personID);
            customerStmt.setDate(2, licenseExpiryDate);
            customerStmt.setString(3, preferredPaymentMethod);
            customerStmt.setString(4, driverLicenseNumber);
            customerStmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Customer added successfully!");
            // Navigate back to ManageCustomersJFrame
            if (parent instanceof ManageCustomersJFrame) {
                ((ManageCustomersJFrame) parent).loadCustomerData();// Optional: Refresh customer table
                this.dispose(); // Close AddCustomerJFrame
                parent.setVisible(true); // Show ManageCustomersJFrame
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error adding customer: " + e.getMessage());
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        if (parent instanceof ManageCustomersJFrame) {
            ((ManageCustomersJFrame) parent).loadCustomerData(); // Refresh customer data
        }
        this.dispose();
        parent.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // For independent testing, pass null as MainMenuJFrame is not needed
                ManageCustomersJFrame manageCustomersFrame = new ManageCustomersJFrame(null);
                new AddCustomerJFrame(manageCustomersFrame).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox<String> ComboAddress;
    private javax.swing.JComboBox<String> ComboGender;
    private javax.swing.JComboBox<String> ComboPreferredPM;
    private javax.swing.JTextField TxtDLN;
    private javax.swing.JTextField TxtEmail;
    private javax.swing.JTextField TxtFirstName;
    private javax.swing.JTextField TxtLED;
    private javax.swing.JTextField TxtLastName;
    private javax.swing.JTextField TxtNationality;
    private javax.swing.JTextField TxtPhoneNumber;
    private javax.swing.JTextField TxtdateOfBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
